name: "Test setup-openlane Action"
on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: test setup-openlane action
        uses: ./
        with:
          version: '0.38.0'
          token:  "$OPENLANE_API_TOKEN"
          add_to_path: 'true'
      - run: openlane version
