name: "Test setup-openlane Action"
on:
  - pull_request_target
  - push: 
      branches:
        - main
  - workflow_dispatch: # manual trigger from any tag or branch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test setup-openlane action
        uses: ./
        with:
          version: '0.40.2'
          token:  "$OPENLANE_API_TOKEN"
          add_to_path: 'true'
      - run: openlane --version
